owner: yevhenv95
repo: KyribaTopaz

schedule: "0 * * * *"

sites:
  - name: Kyriba Topaz – Web App
    url: https://topaz.treasury-factory.com
    maxResponseTime: 4000
    expectedStatus: 200

status-website:
  baseUrl: /KyribaTopaz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Kyriba Topaz Uptime
  introTitle: "**Kyriba Topaz Status Page**"
  introMessage: Real-time performance and availability monitoring of the Topaz platform.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/yevhenv95/KyribaTopaz
